# permissions for end users to edit quotas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: quota-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: quota-limit
    app.kubernetes.io/part-of: quota-limit
    app.kubernetes.io/managed-by: kustomize
  name: quota-editor-role
rules:
- apiGroups:
  - resource.tutorial.controller.io
  resources:
  - quotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.tutorial.controller.io
  resources:
  - quotas/status
  verbs:
  - get
